name       : tdrop
version    : 0.3.0
release    : 1
source     :
    - https://github.com/noctuid/tdrop/archive/0.3.0.tar.gz : 127467b5e5b8d0b973297fb2a84494e89c82f739dc2126867922635a8c0b7c9a
license    : BSD-2-Clause
component  : desktop
summary    : A Glorified WM-Independent Dropdown Creator 
description: |
    Create Dropdowns for almost all available programs on different window managers. Supports sizing dropdowns, tiling multiple dropdowns, multiple dropdowns of the same program and many more.
rundeps  :
    - xprop
    - xwininfo
    - xdotool
    - tmux
install    : |
    %make_install PREFIX=/usr
