name       : tdrop
version    : 0.5.0
release    : 2
source     :
    - https://github.com/noctuid/tdrop/archive/refs/tags/0.5.0.tar.gz : ac37c76cb936d8e4c1c0aba5874999e09b8acbe07a2e23e8181114bd4a2a0a5d
license    : BSD-2-Clause
component  : desktop
summary    : A Glorified WM-Independent Dropdown Creator
description: |
    Create Dropdowns for almost all available programs on different window managers. Supports sizing dropdowns, tiling multiple dropdowns, multiple dropdowns of the same program and many more.
rundeps    :
    - xprop
    - xwininfo
    - xdotool
    - tmux
install    : |
    %make_install PREFIX=/usr
